name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm install
      - name: Ensure the integrity of packages from the public npm registry
        run: npm audit signatures
      - name: Release
        uses: codfish/semantic-release-action@v5
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_TOKEN }}
      - run: echo ${{ steps.semantic.outputs.release-version }}

      - run: echo "$OUTPUTS"
        env:
          OUTPUTS: ${{ toJson(steps.semantic.outputs) }}

      - uses: codfish/some-other-action@v1
        with:
          release-version: ${{ steps.semantic.outputs.release-version }}